[[team]]
name = "Laura Janda"
picture = "janda.jpg"
homepage = "http://ansatte.uit.no/laura.janda/"

[[team]]
name = "Radovan Bast"
picture = "bast.jpg"
homepage = "https://bast.fr"

[[team]]
name = "Vladimír Benko"
picture = "benko.jpg"
homepage = "http://www.juls.savba.sk/~vladob"

[[team]]
name = "Patrick Cullen"
picture = "cullen.jpg"
homepage = "https://www.nupi.no/en/About-NUPI/Employees/Researchers/Patrick-J.-Cullen"

[[team]]
name = "Václav Cvrček"
picture = "cvrcek.jpg"
homepage = "https://ucnk.ff.cuni.cz/cs/ustav/lide/vaclav-cvrcek/"

[[team]]
name = "Gunhild Hoogensen Gjørv"
picture = "hoogensen-gjoerv.jpg"
homepage = "https://uit.no/ansatte/person?p_document_id=42266"

[[team]]
name = "Tore Nesset"
picture = "nesset.jpg"
homepage = "http://uit.no/om/enhet/ansatte/person?p_document_id=41533&p_dimension_id=210121"

[[team]]
name = "Holger Pötzsch"
picture = "poetzsch.jpg"
homepage = "https://en.uit.no/om/enhet/ansatte/person?p_document_id=43820&p_dimension_id=210121"

[[team]]
name = "Andrei Rogatchevski"
picture = "rogatchevski.jpg"
homepage = "https://uit.no/ansatte/person?p_document_id=361780"

[[team]]
name = "Josef Šlerka"
picture = "slerka.jpg"
homepage = "https://uisk.ff.cuni.cz/cs/o-ustavu/vyucujici/josef-slerka/"

[[team]]
name = "Trond Trosterud"
picture = "trosterud.jpg"
homepage = "https://uit.no/ansatte/person?p_document_id=41545"

[[team]]
name = "Masako Ueda Fidler"
picture = "ueda-fidler.jpg"
homepage = "https://vivo.brown.edu/display/mufidler"
